### ISSUE TITLE
Unique flow id

### ISSUE THREAD

**Issue by dayofbrian** [BrianAnderson-BAJL/BAJL-Flow#1]
Thought about introducing a unique flow id to store in the XML, and that would be used to replace flows during runtime. Right now it is using the path/filename for this purpose. Not sure it is a good idea, would prevent someone from copying the file and making minor changes to it. They would need to use the designer to 'save as' to ensure a new unique id was created for the flow.

**Comment by BrianAnderson-BAJL** [comment]
Decided not to do this. I like using the file name as the unique identifier.
